export const SCREEN_NAMES = {
  Home: 'Home',
  ViewStock: 'ViewStock',
};

export const dataList = [
  {
    '1. symbol': 'TEAF',
    '2. name': 'Ecofin Sustainable and Social Impact Term Fund',
    '3. type': 'Equity',
    '4. region': 'United States',
    '5. marketOpen': '09:30',
    '6. marketClose': '16:00',
    '7. timezone': 'UTC-04',
    '8. currency': 'USD',
    '9. matchScore': '0.6667',
  },
  {
    '1. symbol': 'TEAH',
    '2. name': 'Worry Free Tea House Holdings Company',
    '3. type': 'Equity',
    '4. region': 'United States',
    '5. marketOpen': '09:30',
    '6. marketClose': '16:00',
    '7. timezone': 'UTC-04',
    '8. currency': 'USD',
    '9. matchScore': '0.6667',
  },
  {
    '1. symbol': 'TEAM',
    '2. name': 'Atlassian Corporation Plc - Class A',
    '3. type': 'Equity',
    '4. region': 'United States',
    '5. marketOpen': '09:30',
    '6. marketClose': '16:00',
    '7. timezone': 'UTC-04',
    '8. currency': 'USD',
    '9. matchScore': '0.6667',
  },
  {
    '1. symbol': 'TEAR',
    '2. name': 'TearLab Corp',
    '3. type': 'Equity',
    '4. region': 'United States',
    '5. marketOpen': '09:30',
    '6. marketClose': '16:00',
    '7. timezone': 'UTC-04',
    '8. currency': 'USD',
    '9. matchScore': '0.6667',
  },
  {
    '1. symbol': 'TE.PAR',
    '2. name': 'Technip Energies N.V',
    '3. type': 'Equity',
    '4. region': 'Paris',
    '5. marketOpen': '09:00',
    '6. marketClose': '17:30',
    '7. timezone': 'UTC+01',
    '8. currency': 'EUR',
    '9. matchScore': '0.5714',
  },
  {
    '1. symbol': 'TE1.FRK',
    '2. name': 'Bio-Techne Corporation',
    '3. type': 'Equity',
    '4. region': 'Frankfurt',
    '5. marketOpen': '08:00',
    '6. marketClose': '20:00',
    '7. timezone': 'UTC+01',
    '8. currency': 'EUR',
    '9. matchScore': '0.5714',
  },
  {
    '1. symbol': 'TE7.FRK',
    '2. name': 'Tenable Holdings Inc',
    '3. type': 'Equity',
    '4. region': 'Frankfurt',
    '5. marketOpen': '08:00',
    '6. marketClose': '20:00',
    '7. timezone': 'UTC+01',
    '8. currency': 'EUR',
    '9. matchScore': '0.5714',
  },
  {
    '1. symbol': 'TEAFX',
    '2. name': 'TAX EXEMPT BOND FUND OF AMERICA CLASS F2',
    '3. type': 'Mutual Fund',
    '4. region': 'United States',
    '5. marketOpen': '09:30',
    '6. marketClose': '16:00',
    '7. timezone': 'UTC-04',
    '8. currency': 'USD',
    '9. matchScore': '0.5714',
  },
  {
    '1. symbol': 'TEA.TRV',
    '2. name': 'Tearlach Resources Limited',
    '3. type': 'Equity',
    '4. region': 'Toronto Venture',
    '5. marketOpen': '09:30',
    '6. marketClose': '16:00',
    '7. timezone': 'UTC-05',
    '8. currency': 'CAD',
    '9. matchScore': '0.5714',
  },
  {
    '1. symbol': 'TEAM.LON',
    '2. name': 'TEAM plc',
    '3. type': 'Equity',
    '4. region': 'United Kingdom',
    '5. marketOpen': '08:00',
    '6. marketClose': '16:30',
    '7. timezone': 'UTC+00',
    '8. currency': 'GBX',
    '9. matchScore': '0.5000',
  },
];
